export const dataTable = [
    {
        authorNameOriginal: "name",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "arabic",
        genre: "genre",
        textType: "print",
        date: "date",
    },
    {
        authorNameOriginal: "print",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "turkish",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "LIAMBAKAR",
        authorNameTranslit: "query",
        titleOriginal: "title",
        titleTranslit: "translittitle3",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "zSujoy",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "Turkish",
        genre: "genre",
        textType: "print",
        date: "date",
    },
    {
        authorNameOriginal: "zzname4",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name5",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "print",
        date: "date",
    },
    {
        authorNameOriginal: "name6",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "Arabic",
        genre: "genreQuery",
        textType: "MANUscript",
        date: "date",
    },
    {
        authorNameOriginal: "name7",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "manuscript",
        date: "date",
    },
];
