export const dataTable = [
    {
        authorNameOriginal: "name",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name1",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name2",
        authorNameTranslit: "query",
        titleOriginal: "title",
        titleTranslit: "translittitle3",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name3",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name4",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name5",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name6",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genreQuery",
        textType: "type",
        date: "date",
    },
    {
        authorNameOriginal: "name7",
        authorNameTranslit: "translitname",
        titleOriginal: "title",
        titleTranslit: "translittitle",
        language: "language",
        genre: "genre",
        textType: "type",
        date: "date",
    },
];
